version: 2

sources:
  - name: jaffle_shop
    tables:
      - name: orders
      - name: customers
  - name: stripe
    tables:
      - name: payments
  - name: knoema_economy_data_atlas
    database: knoema_economy_data_atlas
    schema: economy
    tables:
      - name: exratescc2018
      - name: usindssp2020
